# Generated by Django 4.2.29 on 2026-03-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('in_Count', models.IntegerField()),
                ('out_Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('security_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=2)),
                ('phone_no', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('out_time', models.DateTimeField()),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('student_roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpass.student')),
            ],
        ),
    ]
