# Generated by Django 6.0.3 on 2026-03-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Data',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
                ('out_Count', models.IntegerField(default=0)),
                ('in_Count', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('security_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=2)),
                ('phone_no', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('qr_code', models.CharField(max_length=100, null=True, unique=True)),
                ('out_time', models.DateTimeField(null=True)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('student_roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpass.student')),
            ],
        ),
    ]
