# Generated by Django 4.2.29 on 2026-03-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
